### ISSUE TITLE
CVPR presentation slides

### ISSUE THREAD

**Issue by yanconglin** [WiseLabCMU/dart#4]
Hi, congrats on the great work.
I was wondering if it is possible to share the CVPR presentation slides. 
Many thanks!

**Comment by thetianshuhuang** [comment]
We're working on it! Unfortunately, the slides have many large videos embedded, so we can't easily export it without ending up with slides covered with black boxes or unrepresentative stills. Since CVPR neglected to record the talks, we will record our own version soon which will include the slides with the videos playing.
